{% set name = "hatch-deps-selector" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch_deps_selector-{{ version }}.tar.gz
  sha256: 6d87d62c83292ce356e9f1b0386dd4f88de7f2ab0e52bfe476fc3e4ee2421e61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - hatchling

test:
  imports:
    - hatch_deps_selector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-book/hatch-deps-selector
  summary: Select variants of your dependencies with environment variables
  dev_url: https://github.com/jupyter-book/hatch-deps-selector
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
